[theme]
primaryColor = "#00ff00"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#1f1f1f"
textColor = "#ffffff"
font = "sans serif"

[client]
showErrorDetails = false

[logger]
level = "warning"

[server]
port = 8501
headless = false
maxUploadSize = 200

[browser]
ServerAddress = "localhost"
